INSERT INTO achievement (title, description, rarity, points, created_at, updated_at)
VALUES
    ('ORGANIZER', 'For 100 invitations', 3, 15, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('LIBRARIAN', 'For 10 post albums', 2, 10, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('OPINION_LEADER', 'For 1000 posts', 4, 20, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('ALL_LOVE', 'For 1000 likes', 3, 20, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('CONGLOMERATE', 'For 20 teams', 3, 15, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('EVIL_COMMENTER', 'For 100 comments', 2, 10, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('BUSINESSMAN', 'For 5 projects', 2, 10, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('BLOGGER', 'For 1000 subscribers', 2, 15, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('FOLLOWERS', 'For 100 subscribers', 1, 10, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('RECURSION', 'For 30 achievements', 4, 20, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('WHOEVER', 'For 100 skills', 4, 20, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
