INSERT INTO achievement (type, title, description, rarity, points, created_at, updated_at)
VALUES
    ('GOAL', 'COLLECTOR', 'For 100 goals', 3, 15, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('TASK', 'MR PRODUCTIVITY', 'For 1000 finished tasks', 4, 20, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('COMMENT', 'EXPERT', 'For 1000 comments', 1, 5, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('MENTEE', 'SENSEI', 'For 30 mentees', 4, 20, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('MANAGER', 'MANAGER', 'For 10 teams', 2, 10, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('SUBSCRIBER', 'CELEBRITY', 'For 1 000 000 subscribers', 4, 20, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('POST', 'ROOKY_WRITER', 'For first posts published', 0, 2, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('POST', 'BEGINNER_WRITER', 'For 10 posts published', 1, 5, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('POST', 'MIDDLE_WRITER', 'For 50 posts published', 2, 10, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('POST', 'SENIOR_WRITER', 'For 100 posts published', 3, 15, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('POST', 'LEV_TOLSTOY', 'For 500 posts published', 4, 20, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('ACCOUNT', 'HANDSOME', 'For uploaded profile photo', 0, 2, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)